config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]
  devise_for :users, path:'', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show, :edit] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'portfolio/:id/edit', to: 'portfolios#edit', as: 'portfolio_edit'
  get 'portfolios/data_engineering', to: 'portfolios#data_engineering'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'


end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder

  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :subtitle, :body

  has_one_attached :image

  def self.data_engineering
    where(subtitle: "Data Engineering")
  end

  def self.by_position
    order("position ASC")
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index, :data_engineering], user: {except: [:destroy, :new, :update, :edit]}, site_admin: :all
  layout 'portfolio'

  def index
    @portfolios = Portfolio.with_attached_image.by_position
    @page_title = 'Things I did'
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position] )
    end
    render nothing: true
  end

  def data_engineering
    @portfolios = Portfolio.data_engineering
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @page_title = @portfolio.title
  end

  def edit
    3.times { @portfolio.technologies.build }
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(
                                        :title,
                                        :subtitle,
                                        :body,
                                        :image,
                                        technologies_attributes: [:name, :id, :_destry]
                                      )
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def set_defaults
    if self.class == Portfolio
      self.main_image ||= image_generator('600', '400')
      self.thumb_image ||= image_generator('350', '200')
    elsif self.class == Skill
      self.badge ||= image_generator('250', '250')
    end
  end

  def portfolio_img(img, type)
    p img.class
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |f| %>
  <% if @portfolio.errors.any? %>
    <% @portfolio.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload an image file <%= f.file_field :image, direct_upload: true, style: 'display:none;' %>
        </label>
      </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Technolgies Used:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>

      <div class='add-technology'>
        <%= link_to_add_association 'Add Technology', f, :technologies %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<div class="col-md-4">
  <div class="card portfolio-box" data-id="<%= portfolio.id %>">
    <div class="portfolio-image">
      <% if portfolio.image.attached? %>
      <a href='<%= portfolio_show_path(portfolio) %>'>
        <%= image_tag portfolio.image, width: '100%' %>
      <% end %>
      </a>
    </div>
    <p class="card-text">
      <span><%= link_to portfolio.title, portfolio_show_path(portfolio), class: "portfolio-title-link" %></span> &nbsp; | &nbsp; <%= portfolio.subtitle %> &nbsp; | &nbsp; <%= portfolio.position %>
    </p>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/data_engineering.html.erb
<h1>Data Engineering Portfolio Items</h1>

<%= link_to "Create New Porfofio", new_portfolio_path h if logged_in?(:site_admin) %>

<% @portfolios.each do |portfolio| %>
  <h3><%= link_to portfolio.title , portfolio_show_path(portfolio) %></h3>
  <%= image_tag portfolio.thumb_image unless portfolio.thumb_image.nil? %>
  <h4><%= portfolio.subtitle %></h4>
  <p><%= portfolio.body %></p>
  <%= link_to "Edit portfolio", portfolio_edit_path(portfolio) %>
  <br>
  <%= link_to "Delete portfolio", portfolio_path(portfolio), method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portfolio: @portfolio %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <%= source_helper("alert alert-warning") %>

    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio', collection: @portfolios %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio: @portfolio %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <% if @portfolio.image.attached? %>
      <%= image_tag @portfolio.image, width: '100%' %>
      <% end %>
    </div>

    <div class="col-md-5">
      <h1><%= @portfolio.title %></h1>

      <hr>

      <em><%= @portfolio.subtitle %></em>

      <p><%= @portfolio.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <% @portfolio.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <div class="">
          <%= link_to "Edit Item", portfolio_edit_path(@portfolio), class: 'btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
</div>