config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]
  devise_for :users, path:'', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show, :edit] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'portfolio/:id/edit', to: 'portfolios#edit', as: 'portfolio_edit'
  get 'portfolios/data_engineering', to: 'portfolios#data_engineering'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'


end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <%= source_helper('application') %>
  <div class="inner">
    <h3 class="masthead-brand">Benjamin Marquis</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <a href="#">Back to top</a>
  </p>
  <p>
    <%= copyright_generator %>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">A couple articles i wrote.</p>
    <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>A couple of articles I wrote about things I like. </p>
    <p>(And during my short carrier as a content writer.) </p>
    <h4>Topics:</h4>
    <% @side_bar_topics.each do |topic| %>
    <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>
  <%= source_helper("alert alert-info blog-sidebar-source") %>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/BjMrq"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.instagram.com/bjmrq"><%= fa_icon "instagram" %></a></li>
      <li><a href="https://www.linkedin.com/in/benjamin-marquis-6956b367/?locale=en_US"><%= fa_icon "linkedin" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class='<%= location %>'>
  <div><%= link_to 'Home', root_path %></div>
  <div><%= link_to 'About Me', about_path %></div>
  <div><%= link_to 'Contact', contact_path %></div>
  <div><%= link_to 'Blog', blogs_path %></div>
  <div><%= link_to 'Portfolio', portfolios_path %></div>
</div>

app/views/shared/_porfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Portfolio</h1>
    <p class="lead text-muted">In this portfolio I've listed some of my favorite projects that I've built through the years. These application capture a wide range of the applications that love to develop, including: web and mobile applications, enterprise projects, machine learning projects, and tools used by millions of users each day.</p>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Portfolio</h1>
    <p class="lead text-muted">In this portfolio I've listed some of my favorite projects that I've built through the years. These application capture a wide range of the applications that love to develop, including: web and mobile applications, enterprise projects, machine learning projects, and tools used by millions of users each day.</p>
    <p>
      <%= link_to 'Find Out More About Me', about_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">In this portfolio I've listed some of my favorite projects that I've built through the years. These application capture a wide range of the applications that love to develop, including: web and mobile applications, enterprise projects, machine learning projects, and tools used by millions of users each day.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <%= link_to "Benjamin Marquis", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>